In [15]:
import numpy as np


#1 shape matrix
mat_1= np.array([[2]])
print(mat_1,"\n")

#2 shape matrix
mat_2= np.array([[2,1],[2,3]])
print(mat_2,"\n")

#2 shape matrix
mat_3= np.array([[22,3,4],[1,3,2],[2,3,4]])
print(mat_3,"\n")

[[2]] 

[[2 1]
 [2 3]] 

[[22  3  4]
 [ 1  3  2]
 [ 2  3  4]] 



In [24]:
mat_1 = np.random.rand(3,4)
print(mat_1)

[[0.64514329 0.76564928 0.81445418 0.76650947]
 [0.96201483 0.3035253  0.51809577 0.75216937]
 [0.03528214 0.53862912 0.85286343 0.11123558]]


In [50]:
mat_2 = np.random.randint(100,size = (4,5))
print(mat_2)

[[37 53 24 42 28]
 [13 24 56 22 59]
 [37 79 28 64 59]
 [39 54 22 71 67]]


In [30]:
mat_3 = np.ones((4,4))
print(mat_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
mat_4 = np.zeros((4,4),dtype = int)
print(mat_4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [38]:
mat_5 = np.eye(4,4)
print(mat_5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
mat_2 = np.random.randint(100,size = (4,5))
print(mat_2)

[[56 32 47 27 66]
 [ 2 85 28 38 19]
 [83 78 11 78 23]
 [89 74 69 23  2]]


In [41]:
trans = np.transpose(mat_2)
print(trans)

[[56  2 83 89]
 [32 85 78 74]
 [47 28 11 69]
 [27 38 78 23]
 [66 19 23  2]]


#opeartion in  matrix

In [53]:
#addition in matrix

mat_1 = np.random.randint(100,size = (3,3))
mat_2 = np.random.randint(100,size = (3,3))
print(mat_1,"\n")
print(mat_2)

[[20 56 26]
 [26 10 51]
 [40 37  8]] 

[[45 46 13]
 [ 4 72 98]
 [16  7 85]]


In [57]:
add  = np.add(mat_1,mat_2)
print(add)

[[ 65 102  39]
 [ 30  82 149]
 [ 56  44  93]]


In [59]:
sub = np.subtract(mat_1,mat_2)
print(sub)

[[-25  10  13]
 [ 22 -62 -47]
 [ 24  30 -77]]


In [60]:
mul = np.dot(mat_1,mat_2)
print(mul)

[[1540 5134 7958]
 [2026 2273 5653]
 [2076 4560 4826]]
